---
title: "PS270 Final Project"
author: "Ryan Konet"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project proposal

In the last three presidential elections in the United States, which combinations of identities by age, gender, race, and religion saw the biggest shifts from 2016 to 2024 in either direction? I believe that the greatest shift toward democrat presidential tickets (Clinton-Kane, Biden-Harris, Harris-Walz) will be young females, certain racial minorities, and atheists. I believe the greatest shift toward republican presidential tickets (Trump-Pence, Trump-Pence, Trump-Vance) will be young men, Whites and Hispanics, and Christian. The explanatory variables are age, gender, race, religion, and the combinations that these variables can make as compounds of intersectional identities. Each variable will exist across all three elections and be compared from election to election and the change will be measured. The outcome variable, which is the percent vote for either candidate (some third parties might be listed in order to see if there were any spoilers that could effect the phenomena), will also be adjusted proportionally for the percent vote in the election as a whole in order to avoid winning elections skewing the phenomena. Support or disapproval of my hypothesis is contigent on whether or not those groups or groups that are similar turn out to have the biggest change.

Below is the 2024 study for reference. Though the similar 2016, 2020 studies will be uploaded in the future.
```{r}
library(tidyverse)
pres_2020 <- read_csv("pres_data/2020_US_County_Level_Presidential_Results.csv")
pres_2020 <- pres_2020 |> select(-votes_dem, -per_dem, -diff, -per_point_diff) |> rename(votes_gop_2020 = votes_gop, per_gop_2020 = per_gop, total_votes_2020 = total_votes)
pres_2024 <- read_csv("pres_data/2024_US_County_Level_Presidential_Results.csv")
pres_2024 <- pres_2024 |> select(-votes_dem, -per_dem, -diff, -per_point_diff) |> rename(votes_gop_2024 = votes_gop, per_gop_2024 = per_gop, total_votes_2024 = total_votes)
pop_2024 <- read_csv("pop_data/co-est2024-alldata.csv")
percent_gop <- left_join(pres_2020, pres_2024)

head(percent_gop)
```


